kind: pipeline
name: default

steps:
- name: docker image build
  image: plugins/docker
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  settings:
    repo: foo/bar
    tags: latest
