FROM maven:3.3.3-jdk-8

ENV APP_HOME /app/ 
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# Get all the downloads out of the way
ADD pom.xml  $APP_HOME
RUN ["mvn","verify","clean","--fail-never"] 

# Mount/copy/add source to $APP_HOME and run maven something (e.g. verify)
CMD ["mvn", "package"]
